# Generated by Django 3.0.5 on 2021-05-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeMetadata',
            fields=[
                ('videoId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('publishTimestamp', models.DateTimeField(verbose_name='Publish Timestamp')),
                ('thumbnailUrl', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddIndex(
            model_name='youtubemetadata',
            index=models.Index(fields=['-publishTimestamp'], name='youtube_you_publish_ede8d7_idx'),
        ),
    ]
